### ISSUE TITLE
Earthquake depths 

### ISSUE THREAD

**Issue by jrekoske** [DOI-USGS/ghsc-esi-groundmotion-processing#1]
A small issue I noticed is that earthquake depths that already in km are being divided by 1000 when requesting by event ID. For example,

```python 
from gmprocess.utils.event import get_event_dict
get_event_dict('ci14383980')
```
returns

```python
{'id': 'ci14383980',
 'time': 2008-07-29T18:42:15.670000Z,
 'lat': 33.9485,
 'lon': -117.7663333,
 'depth': 0.015503,
 'magnitude': 5.44,
 'magnitude_type': 'mw'}
```

when the depth is 15.5 km. The issue propagates into the flat files which state the depth has units of km. The divide by 1000 happens here 

https://github.com/DOI-USGS/ghsc-esi-groundmotion-processing/blob/78a46da6ba3eefca909d152d5d443e593ad3002d/src/gmprocess/utils/event.py#L200

**Comment by gferragu** [comment]
Hey @jrekoske, thanks for making the issue and also for pinging the dev email account to bump this. Problems with conversions from `km` to `m` and vice versa have popped up a few times recently and, despite seemingly being fixed, we've seen further issues arise.

I've made an issue for this on the USGS Gitlab repo for gmprocess and I'm going to pin down all the places conversions occur to hopefully make this less of a headache.

**Comment by emthompson-usgs** [comment]
Thanks @jrekoske. Sorry it took us so long to get to this. It is fixed now with this merge: 
https://code.usgs.gov/ghsc/esi/groundmotion-processing/-/merge_requests/1221
